# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('twi_id', models.CharField(db_index=True, max_length=30, null=True, unique=True)),
                ('twi_token', models.CharField(db_index=True, max_length=120, null=True)),
                ('twi_token_expire', models.DateTimeField(null=True)),
                ('wei_id', models.CharField(db_index=True, max_length=30, null=True, unique=True)),
                ('wei_token', models.CharField(db_index=True, max_length=60, null=True)),
                ('wei_token_expire', models.DateTimeField(null=True)),
                ('joined_at', models.DateTimeField()),
            ],
        ),
    ]
