# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160710_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twi_token_expire',
        ),
        migrations.AddField(
            model_name='user',
            name='twi_token_secret',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twi_token',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wei_token',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
