# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160712_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
    ]
