# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twi_head',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twi_tail',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wei_head',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wei_tail',
            field=models.BigIntegerField(null=True),
        ),
    ]
