"""initial revision

Revision ID: 0dd0c293ec6e
Revises: 
Create Date: 2016-07-15 20:28:10.369870

"""

# revision identifiers, used by Alembic.
revision = '0dd0c293ec6e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('join', sa.DateTime(), nullable=True),
    sa.Column('twi_id', sa.Integer(), nullable=True),
    sa.Column('twi_token', sa.String(length=60), nullable=True),
    sa.Column('twi_secret', sa.String(length=120), nullable=True),
    sa.Column('twi_max', sa.BigInteger(), nullable=True),
    sa.Column('twi_since', sa.BigInteger(), nullable=True),
    sa.Column('wei_id', sa.Integer(), nullable=True),
    sa.Column('wei_token', sa.String(length=60), nullable=True),
    sa.Column('wei_max', sa.BigInteger(), nullable=True),
    sa.Column('wei_since', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
