"""record max_id and since_id in redis session, delete these columns from db

Revision ID: 7b0e90baa1dd
Revises: d4b89bb0b3ff
Create Date: 2016-07-25 10:03:03.091665

"""

# revision identifiers, used by Alembic.
revision = '7b0e90baa1dd'
down_revision = 'd4b89bb0b3ff'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'wei_since')
    op.drop_column('users', 'twi_max')
    op.drop_column('users', 'twi_since')
    op.drop_column('users', 'wei_max')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('wei_max', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twi_since', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twi_max', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('wei_since', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    ### end Alembic commands ###
