"""empty message

Revision ID: b04b776556ed
Revises: 7b0e90baa1dd
Create Date: 2016-07-25 16:17:26.491009

"""

# revision identifiers, used by Alembic.
revision = 'b04b776556ed'
down_revision = '7b0e90baa1dd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wei_id')
    op.drop_column('users', 'wei_expire')
    op.drop_column('users', 'wei_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wei_token', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('wei_expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('wei_id', sa.BIGINT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
